branches:
  only:
  - master
language: scala
scala:
- 2.10.6
- 2.11.7
jdk:
- openjdk7
sudo: false
env:
  global:
  # BINTRAY_USER=divtxt
  - secure: vHJRLAto9gcvs9JyYG9wGUXvjykn0iBef6+qegDdCNJZv30UOwJc6C22/Nk5LaKqNy6ELZzgPa9opNY26iYvmaZ5ccT/kfKJMwX+CSYdKWRG6EM5VT0C7B2/x5HTsCKfzRtwonipf3VYseat4/6yOf7ZUveFJI4K9vKLdsTvk/YQuOqj9pcE/lAJqpNj1M1IEHcRd75kv9ST62WxK12xfcwmgHPx2z5sFGaul8dhoPGnCRCAEj8k4wFh8WJtwy0kGjGmlELQ4+19Tl9WteearbiX7ZbbnxdZx8wOPQL7UUHvnXxrzJu+hSdeVUImihwOjX7J6zNO08VV6OblqjAEOVHtIr3QYlbqYVEbU7s+YWtkOcaO1+ZV1MRRd0ayqv8l+kzQm6r6GnvfK0Y8coA4UZ5gro9bN95lwis1INX0QQo+/wIWqoL0VoZoQfi5ylJzrp8bDEstQ4ePVjaTC8jkQFyR/M7MQhoFA9pCqGgtl9PQ2K07MXXOI8eliaqhu4jQRFWvOX0WJHRUExiupsN1yTc5O4xc/bhD012vYtT/C5xRrWfJ5YPLAN94KLgNDu2nSLxIvhWMTwwXti8/RMSznEM+L6C024CVgoEzsVFyb6SzZJMxmbGGD7QX6BSXiOfIDpUKnojuxgUzpKm1xB7/lGskRNCeO0GZ/hOfmQ8RZlI=
  # BINTRAY_API_KEY=...
  - secure: d2wLnxFfKPrII4ZtXIVZdm224WVuHeebGN0Rg+jUBkeu3azFKywId6bNnTbzwnahB/JuKZc3JlozLX+A2L6EPQpvbXPNsClPz00pQEkyG1hkLCUcaads30C9/PUqE68S9dHlGGtzxv43jP+TIBQuGCZrq5J/9LTpzXphyaWmUYJm5p1DRD9YsIKivLMNs04gEzFkAXHK2rmABq3nlL7oYHK6ktFxjtOAwXq5EmW2u2rWHOYUtUfCF1zzBLyEmZ1klVPFm4ROQGXHNBn92H/M7mkfc9alkR95X9cjjnTtimcT2BOPhUBbYYVkc8oIX228wL5mvuGZ001G5VDFt6/YBSv3yEJv0ZFBhKpVfFoAsr3NNetzm0fEMJRBxRknj4KYx0dzG3asMsDFPRXZV6WQZUSB03aAXfAan+c1Loa4qZrxYEtvtOUuNMUDjVmeBtny/wNNs00THRWe0A0G0w3Ychmm25Qb16P/R8fKcRZlTnbBX35YWztFkvaAsW6zs2DZ0t0S9UqCCRRCfDF8q8Z0PjwB4wgxEIqqkazyhQpozsFxH3bd84eufXb8VKlYVtVGEz0wOiI4hSBb3C9QlAAWslG1UlpeUsSRazplbnVGv+BGkBrjjvvHcpZlnv23QWRBOxtgDR+wFNtiIKVcIBhV0zlTjdlwZ4aSU769zxZlEtg=
  # GIT_USER=divtxt
  - secure: iLiK+KLpW54IGsT7Pe+Kac+v2ZhqS9Dnztat+TvroHGnwXMWbhECKx63mhJazrnmRvfkRMFvWr2Fq81JlEUeMCmv1Bj1ABIRtWBGIrJcN1H/Ys2b2rSloN/Wa6nVMhMh0sd2Rqw1xYk4Sg726iwDD3NUCSpARN4Jd9RFhLBNCyyYJ2/CxI34NInIyDQKvK7xdYfTex/aUshJqhRnvBkejR2ybiecOEFwtbJFnMiB1mnvZc9TmvlikstSZjiBDSeDTzaxoEyVStjSBWiYhw6mhCeXCESpwFPJ9taQZxxg7XSYRU4V6DpOxCjDPl7jg8N4WuP6vEumMt7lDGLCyksPblin4u25PnPzeo+3vWRvv5SpCNeHd8Q5Ze2tWLracLsW8gy4dA2+sz546cucWMdKl3FmRv2cL267I2OSktcMvPKr80TrcNhoktiMPO8AJS2/TgQrN2qTIZqMagJAlH7/6ObdzD1yY8aBNbBlQ6voGtvtvE+ZQRYhmhfnWlWwZepDgjL92hAcAFCjUV+mOVOTEr7SxKY/msJuuRjk5Y82PBVFM7bn/HbG5D7HJz2v5NLoX19SRxOaLn/0OxPANhCrJKySa7if+WcMjIy2EReLQqaDrT5DGs6zdrn2XPBUOD1DB3E2eW9doYyx9YTVeA01/cjwWLecBNNSQMqLB4bPWdw=
  # GIT_API_KEY=...
  - secure: s+ff+NyTQoC4V1cPQQ1Cr9CphR/dRjOb6gmvGsRI4803mbHt9WMGjsP1WsEoppk74KWbN/hOWdJTOTuk3gbW0oBbVhPfTyYRQp76tsfOKDrzGf8n5/s4p5OYFJJTJPkOcjmC1TdLDc9Ifk91QM6axdRU98jQGslF0Epbmdikuwrj0dn8DSyw+tMru+KR6bGwL54UTcGEGE1DJYA2i3De8zX3QIw4tlf+DI3f7iN+UHENEOGs98RxW9Rgc2G7XQDAaPUovj4oshCobfZLVmUCrlVle5mdMnYza6fP27CPSLVCKtYJAzIray5UBUzTrIyeH9OsQctNvHiEinHeZ0lwz+R6/rmEkdaYa3YkUKDUbufdHITumRUeKPLPjHDANt/wxwVrs4Sew9zrm6BrDTQRIqetsVwQ4bXnDLp19joU51NjPb66GpoQGHnSq/rL9A1EKj3Txy0/+Euv0CMSk0SZTzBf2+/DpJcdW5KsgRt2pz4OKoza6ZEBfaRbuTjGCZVEXeqriyH8e9iyQAk0olXqawT41mySLTYHO71+4b9Q7JERo+1/A+crdM+cBrgG/YyCqwrrhK7j7YdVo0siRL5eRb9Ok3cOQcGodJZ2Bkk8hh6w7zWnxd6GE+dDSKqIIDtM0PTlj0PnL6PAvP1/bSLjxw+YtOsQCa82w1SfjVJrTvM=
cache:
  directories:
  - ~/.ivy2
  - ~/travis-deps
  apt: true
before_install:
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/zookeeper | /bin/sh
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/kafka | /bin/sh
before_script:
  - ~/travis-deps/start-zookeeper.sh && sleep 3
  - ~/travis-deps/start-kafka.sh && sleep 3
script:
  - sbt -Dsbt.log.noformat=true -sbt-dir ~/.sbt ++$TRAVIS_SCALA_VERSION test it:test
after_success:
- sh "$TRAVIS_BUILD_DIR/.travis.release.sh"
